<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterSeeder extends Seeder
{
    public function run(): void
    {
        $characters = [
            // ── Protagonistas S.T.A.R.S. / B.S.A.A. ────────────────────────────────
            [
                'name'         => 'Leon S. Kennedy',
                'slug'         => 'leon-s-kennedy',
                'alias'        => null,
                'faction'      => 'Independent',
                'status'       => 'alive',
                'description'  => 'Ex-oficial de la policía de Raccoon City y agente de élite del gobierno de EE.UU. Sobreviviente del brote del virus-T en 1998.',
                'image'        => 'https://sm.ign.com/t/ign_latam/screenshot/default/leons_28sp.1280.jpg',
                'nationality'  => 'Estadounidense',
                'blood_type'   => 'A',
                'height_cm'    => 180,
                'birth_date'   => '1977-02-07',
                'is_playable'  => true,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Claire Redfield',
                'slug'         => 'claire-redfield',
                'alias'        => null,
                'faction'      => 'Independent',
                'status'       => 'alive',
                'description'  => 'Hermana de Chris Redfield y estudiante universitaria. Sobrevivió al brote de Raccoon City junto a Leon, y más tarde se involucró con la Organización TerraSave.',
                'image'        => 'https://static.wikia.nocookie.net/residentevil/images/5/5e/Claire_Redfield_RE2.png/revision/latest?cb=20190214221914&path-prefix=es',
                'nationality'  => 'Estadounidense',
                'blood_type'   => 'B',
                'height_cm'    => 168,
                'birth_date'   => '1979-03-13',
                'is_playable'  => true,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Chris Redfield',
                'slug'         => 'chris-redfield',
                'alias'        => null,
                'faction'      => 'B.S.A.A.',
                'status'       => 'alive',
                'description'  => 'Miembro fundador de la B.S.A.A. y antiguo integrante del equipo S.T.A.R.S. Alpha. Veterano en el combate contra armas biológicas en todo el mundo.',
                'image'        => 'https://i.blogs.es/7c5f53/image-11--compressed/500_333.jpeg',
                'nationality'  => 'Estadounidense',
                'blood_type'   => 'O',
                'height_cm'    => 185,
                'birth_date'   => '1973-07-23',
                'is_playable'  => true,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Jill Valentine',
                'slug'         => 'jill-valentine',
                'alias'        => 'La Maestra de los Desbloqueos',
                'faction'      => 'B.S.A.A.',
                'status'       => 'alive',
                'description'  => 'Co-fundadora de la B.S.A.A. y experta en explosivos. Sobrevivió a la Mansión Spencer, al brote de Raccoon City y a la infección de Wesker.',
                'image'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPWgu5xazXXN52i5EiyPYLxfdUKxIbY-dGnQ&s',
                'nationality'  => 'Estadounidense / Francesa',
                'blood_type'   => 'B',
                'height_cm'    => 166,
                'birth_date'   => '1974-02-14',
                'is_playable'  => true,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Ethan Winters',
                'slug'         => 'ethan-winters',
                'alias'        => null,
                'faction'      => 'Independent',
                'status'       => 'deceased',
                'description'  => 'Ingeniero de software convertido en involuntario héroe. Infectado por el moho Mold, desarrolló capacidades regenerativas únicas. Padre de Rosemary Winters.',
                'image'        => 'https://static.wikia.nocookie.net/godmodes/images/f/f6/Ethan_Winters.png/revision/latest/scale-to-width-down/194?cb=20230112235339',
                'nationality'  => 'Estadounidense',
                'blood_type'   => 'A',
                'height_cm'    => 180,
                'birth_date'   => '1984-07-25',
                'is_playable'  => true,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // ── Villanos ────────────────────────────────────────────────────────────
            [
                'name'         => 'Albert Wesker',
                'slug'         => 'albert-wesker',
                'alias'        => null,
                'faction'      => 'Umbrella',
                'status'       => 'deceased',
                'description'  => 'Antiguo capitán de S.T.A.R.S. y científico de Umbrella. Infectado con el prototipo de virus que le otorgó habilidades sobrehumanas. Ambicionaba convertirse en un ser superior.',
                'image'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIIIF5_RB9Z91-KkGdelgpM23j5Pvb-ALt-w&s',
                'nationality'  => 'Estadounidense',
                'blood_type'   => 'O',
                'height_cm'    => 183,
                'birth_date'   => '1960-01-01',
                'is_playable'  => false,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Oswell E. Spencer',
                'slug'         => 'oswell-e-spencer',
                'alias'        => 'Lord Spencer',
                'faction'      => 'Umbrella',
                'status'       => 'deceased',
                'description'  => 'Cofundador de Umbrella Corporation y arquitecto del proyecto Progenitor. Soñaba con convertirse en el dios de un nuevo mundo de seres superiores.',
                'image'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyhzy1o_2XcdAZXeCY6adF63GhlPJDUaYEzQ&s',
                'nationality'  => 'Europeo',
                'blood_type'   => null,
                'height_cm'    => null,
                'birth_date'   => null,
                'is_playable'  => false,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Nemesis',
                'slug'         => 'nemesis',
                'alias'        => 'Nemesis-T Type',
                'faction'      => 'Umbrella',
                'status'       => 'deceased',
                'description'  => 'Arma biológica avanzada creada por Umbrella para cazar y eliminar a los miembros de S.T.A.R.S. supervivientes del brote de Raccoon City.',
                'image'        => 'https://www.gamerfocus.co/wp-content/uploads/2026/03/nemesis_capcom_figure_builder_01.png',
                'nationality'  => null,
                'blood_type'   => null,
                'height_cm'    => 213,
                'birth_date'   => null,
                'is_playable'  => false,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Alcina Dimitrescu',
                'slug'         => 'alcina-dimitrescu',
                'alias'        => 'Lady Dimitrescu',
                'faction'      => 'Villain',
                'status'       => 'deceased',
                'description'  => 'Aristócrata vampírica de más de 2.9 metros de altura, una de los Cuatro Señores bajo el mando de Mother Miranda. Habita el Castillo Dimitrescu en RE Village.',
                'image'        => 'https://static.wikia.nocookie.net/vampires/images/6/66/7af863c6-f919-4986-8f1d-e0c41e2ac93e.webp/revision/latest?cb=20240402153015',
                'nationality'  => 'Europea del Este',
                'blood_type'   => null,
                'height_cm'    => 296,
                'birth_date'   => '1914-01-01',
                'is_playable'  => false,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Mother Miranda',
                'slug'         => 'mother-miranda',
                'alias'        => 'La Madre',
                'faction'      => 'Villain',
                'status'       => 'deceased',
                'description'  => 'Antigua investigadora que descubrió la Cadena Micótica y se convirtió en figura religiosa de un pueblo de Europa del Este. Principal antagonista de Resident Evil Village.',
                'image'        => 'https://static.wikia.nocookie.net/residentevil/images/0/06/Miranda_meets_Rosemary.jpg/revision/latest?cb=20230728115717',
                'nationality'  => 'Europea del Este',
                'blood_type'   => null,
                'height_cm'    => 172,
                'birth_date'   => null,
                'is_playable'  => false,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // ── Infectados / Criaturas notables ─────────────────────────────────────
            [
                'name'         => 'Lisa Trevor',
                'slug'         => 'lisa-trevor',
                'alias'        => null,
                'faction'      => 'Infected',
                'status'       => 'unknown',
                'description'  => 'Hija de George Trevor, el arquitecto de la Mansión Spencer. Fue usada como sujeto de prueba por Umbrella durante décadas, desarrollando una resistencia extraordinaria.',
                'image'        => 'https://static.wikia.nocookie.net/residentevil/images/d/de/Lisa004.jpg/revision/latest?cb=20150820201811&path-prefix=es',
                'nationality'  => 'Estadounidense',
                'blood_type'   => null,
                'height_cm'    => null,
                'birth_date'   => '1953-01-01',
                'is_playable'  => false,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // ── Aliados / Secundarios ────────────────────────────────────────────────
            [
                'name'         => 'Ada Wong',
                'slug'         => 'ada-wong',
                'alias'        => null,
                'faction'      => 'Independent',
                'status'       => 'alive',
                'description'  => 'Espía de identidad misteriosa que trabaja para diversas organizaciones secretas. Mantiene una relación ambigua con Leon S. Kennedy a lo largo de múltiples aventuras.',
                'image'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMKxhDFgIq4RfiiBxcLTmaHoVPB7ZBcKydmQ&s',
                'nationality'  => 'Estadounidense / China',
                'blood_type'   => null,
                'height_cm'    => 168,
                'birth_date'   => null,
                'is_playable'  => true,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'Rebecca Chambers',
                'slug'         => 'rebecca-chambers',
                'alias'        => null,
                'faction'      => 'S.T.A.R.S.',
                'status'       => 'alive',
                'description'  => 'Médico y miembro del equipo S.T.A.R.S. Bravo. La más joven del equipo, especializada en medicina de campo. Sobreviviente de los incidentes de Raccoon City.',
                'image'        => 'https://img.somosxbox.com/somosxbox/2020/11/22091933/rebecca-chambers.jpg',
                'nationality'  => 'Estadounidense',
                'blood_type'   => 'A',
                'height_cm'    => 157,
                'birth_date'   => '1978-06-21',
                'is_playable'  => true,
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
        ];

        DB::table('characters')->insert($characters);
    }
}
