<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        $games = [
            [
                'title'        => 'Resident Evil',
                'slug'         => 'resident-evil',
                'release_year' => 1996,
                'platform'     => 'PS1, PC, Saturn',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/7/74/Resident_Evil_PS1_USA.jpg/revision/latest/scale-to-width/360?cb=20210823163310&path-prefix=es',
                'synopsis'     => 'El equipo S.T.A.R.S. Alpha investiga la desaparición del equipo Bravo en los alrededores de Raccoon City, terminando atrapados en una mansión llena de horrores.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 2',
                'slug'         => 'resident-evil-2',
                'release_year' => 1998,
                'platform'     => 'PS1, PC, N64',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/f/f9/Resident_Evil_2_Caratula_USA.png/revision/latest?cb=20191002001320&path-prefix=es',
                'synopsis'     => 'Leon S. Kennedy y Claire Redfield llegan a una Raccoon City devastada por un brote del virus-T, buscando sobrevivir y escapar de la ciudad.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 3: Nemesis',
                'slug'         => 'resident-evil-3-nemesis',
                'release_year' => 1999,
                'platform'     => 'PS1, PC, Dreamcast',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/e/e5/RE3_GameCube.jpg/revision/latest/scale-to-width/360?cb=20180816160245&path-prefix=es',
                'synopsis'     => 'Jill Valentine intenta escapar de Raccoon City mientras es perseguida implacablemente por Nemesis, una arma biológica de Umbrella.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil – Code: Veronica',
                'slug'         => 'resident-evil-code-veronica',
                'release_year' => 2000,
                'platform'     => 'Dreamcast, PS2',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/1/19/RECV_Dreamcast_USA.jpg/revision/latest/scale-to-width-down/1200?cb=20190825180537&path-prefix=es',
                'synopsis'     => 'Claire Redfield es capturada y trasladada a la prisión de Rockfort Island, donde debe enfrentarse a los hermanos Ashford y a un nuevo brote vírico.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 4',
                'slug'         => 'resident-evil-4',
                'release_year' => 2005,
                'platform'     => 'GameCube, PS2, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/7/76/Resident_Evil_4_GC.jpg/revision/latest/scale-to-width-down/1200?cb=20250709064905&path-prefix=es',
                'synopsis'     => 'Leon S. Kennedy es enviado a España para rescatar a la hija del presidente de EE.UU., encontrándose con Los Iluminados y el parásito Las Plagas.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 5',
                'slug'         => 'resident-evil-5',
                'release_year' => 2009,
                'platform'     => 'PS3, Xbox 360, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/1/1f/RE5_PS3_cover.jpg/revision/latest/scale-to-width-down/1200?cb=20180409154458&path-prefix=es',
                'synopsis'     => 'Chris Redfield y Sheva Alomar investigan un tráfico de armas biológicas en Kijuju, África, descubriendo la implicación de Albert Wesker.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 6',
                'slug'         => 'resident-evil-6',
                'release_year' => 2012,
                'platform'     => 'PS3, Xbox 360, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/f/fd/RE6_X360_EUR.jpg/revision/latest/scale-to-width-down/250?cb=20200302022102&path-prefix=es',
                'synopsis'     => 'Múltiples agentes afrontan una amenaza bioterrorista global perpetrada por Neo-Umbrella y el misterioso agente C.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 7: Biohazard',
                'slug'         => 'resident-evil-7-biohazard',
                'release_year' => 2017,
                'platform'     => 'PS4, Xbox One, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/1/17/RE7_USA.jpg/revision/latest?cb=20180824003730&path-prefix=es',
                'synopsis'     => 'Ethan Winters viaja a Louisiana para encontrar a su esposa desaparecida, terminando atrapado en la granja de la familia Baker, infectada por el moho Mold.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil Village',
                'slug'         => 'resident-evil-village',
                'release_year' => 2021,
                'platform'     => 'PS5, Xbox Series X/S, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/c/ca/RE_Village_PS5.png/revision/latest?cb=20210128144751&path-prefix=es',
                'synopsis'     => 'Ethan Winters viaja a un misterioso pueblo de Europa del Este para rescatar a su hija Rose, enfrentándose a los Cuatro Señores bajo el control de Mother Miranda.',
                'canon'        => 'main',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 2 (Remake)',
                'slug'         => 'resident-evil-2-remake',
                'release_year' => 2019,
                'platform'     => 'PS4, Xbox One, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/8/88/RE2_PS4.png/revision/latest?cb=20190214221913&path-prefix=es',
                'synopsis'     => 'Remake del clásico de 1998. Leon y Claire deben sobrevivir a la ciudad de Raccoon completamente infestada, mientras escapan del incansable Mr. X.',
                'canon'        => 'remake',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 3 (Remake)',
                'slug'         => 'resident-evil-3-remake',
                'release_year' => 2020,
                'platform'     => 'PS4, Xbox One, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/c/cd/RE3_remake_PS4.jpg/revision/latest?cb=20200112143143&path-prefix=es',
                'synopsis'     => 'Remake del clásico de 1999. Jill Valentine lucha por sobrevivir en Raccoon City mientras es cazada por Nemesis.',
                'canon'        => 'remake',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil 4 (Remake)',
                'slug'         => 'resident-evil-4-remake',
                'release_year' => 2023,
                'platform'     => 'PS5, PS4, Xbox Series X/S, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/6/62/RE4R_PS5_USA.jpg/revision/latest?cb=20230411182033&path-prefix=es',
                'synopsis'     => 'Remake del aclamado RE4. Leon S. Kennedy viaja a España para rescatar a Ashley Graham, con una narrativa y mecánicas profundamente renovadas.',
                'canon'        => 'remake',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'title'        => 'Resident Evil: Revelations',
                'slug'         => 'resident-evil-revelations',
                'release_year' => 2012,
                'platform'     => '3DS, PS3, Xbox 360, PC',
                'developer'    => 'Capcom',
                'cover_image'  => 'https://static.wikia.nocookie.net/residentevil/images/2/28/Resident_Evil_Revelations_PS4.jpg/revision/latest?cb=20170518115725&path-prefix=es',
                'synopsis'     => 'Jill Valentine y su compañero Parker investigan un crucero abandonado en el Mar Mediterráneo, descubriendo la amenaza del virus T-Abyss.',
                'canon'        => 'spin-off',
                'is_published' => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
        ];

        DB::table('games')->insert($games);
    }
}
